apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot-deployment
  labels:
    name: discord-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      name: discord-bot
  template:
    metadata: 
      labels:
        name: discord-bot
    spec:
      containers:
      - name: discord-bot
        image: jeffreyfreeland/discord-bot:v0.0.4
        env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: bot-token
              key: TOKEN
        volumeMounts:
        - name: config
          mountPath: /app/config/
          readOnly: true
      volumes:
      - name: config
        configMap: 
          name: image-urls-file
          items:
          - key: imageFile
            path: image-urls.txt
